# Minecraft / Fabric properties
# Revisa https://fabricmc.net/develop/ por si hay versiones mas nuevas de estos componentes
minecraft_version=26.2
loader_version=0.17.4
fabric_version=0.154.0+26.2
loom_version=1.16.2

# Mod properties
mod_version=1.0.0
maven_group=com.sunnaicor
archives_base_name=sunna_icor

# Minecraft 26.1+ ya no esta ofuscado y usa Java 25
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
